name: note_app
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  awesome_dialog: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  lottie: ^3.0.0
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  flutter_native_splash: ^2.3.10
  


flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#000000"
  image: "assets/images/1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/lottie/
    - assets/images/
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: tajawal
      fonts:
        - asset: assets/fonts/Cairo.ttf
  
  
  
  
  
  
  
  
  
  
